### ISSUE TITLE
Did not see the inferernce function in this repo.

### ISSUE THREAD

**Issue by CopyNinja1999** [wannaphong/KhanomTan-TTS-v1.0#2]
Thanks for your excellent work. Though I do not know how to infer this model to synthesis audio. Could you please tell me how to do the inference and perhaps add more details in the readme?

**Comment by yurtmete** [comment]
You have to use [coqui](https://github.com/coqui-ai/TTS) for inference. They have all the inference code for this model.

**Comment by wannaphong** [comment]
https://github.com/PyThaiNLP/PyThaiTTS/blob/dev/pythaitts/pretrained/khanomtan_tts.py
